### PR TITLE
Add support for python 3.8 and 3.9, switched docker image to mlupin/docker-lambda

### PR DESCRIPTION
**Pull request by mumblepins**
*Description of changes:*

- Added Python 3.8 and Python 3.9
- Switched docker build image to [mlupin/docker-lambda](https://github.com/mLupine/docker-lambda) 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mumblepins** [comment]
Sister pull request https://github.com/aws-cloudformation/cloudformation-cli/pull/870

**Review by ammokhov — APPROVED** [review]

**Review by prerna-p — APPROVED** [review]

**Review by ammokhov — CHANGES_REQUESTED** [review]
actually to make it 100% backward compatible, lets release cli first and add install requirements to python plugin

```
install_requires=["cloudformation-cli>=0.2.24", "types-dataclasses>=0.1.5"]
```

[ref](https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/blob/master/setup.py#L41)

**Comment by ericzbeard** [comment]
We are going to make a few changes to this PR. We changed the docker image to one hosted in ECR in a PR we merged earlier.

@kddejong don't forget to incorporate changes from https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/pull/145

**Comment by kddejong** [comment]
Closed for replacement by https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/pull/198

**Pull request closed without merging**
