### PR TITLE
Make the support lib easier to install

### PR DESCRIPTION
**Pull request by ikben**
This relates to #50 

By pointing requirements.txt to this repo, we do not need to publish to pypi.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ikben** [comment]
I did not test it thoroughly, so I assume I made an error. I'll try to find my mistake today

**Comment by ikben** [comment]
I'm testing this again, and is now failing for me with this error. I don't remember seeing it before, and it still works when installing directly so I will have to dive deeper into this:
```
Command 'pip install --no-cache-dir --no-color --disable-pip-version-check --upgrade --find-links /project --requirement /project/requirements.txt --target /project/build' in image 'lambci/lambda:build-python3.7' returned non-zero exit status 1
```

**Comment by tobywf** [comment]
that would be the Docker build. are there any other logs? if you set `"use_docker"` to `false` in `.rpdk-config`, it will use pip locally. (for some libraries, especially C extensions, building in Docker makes sure it has the right architecture, which is why we recommend it, but for debugging, doesn't really matter). the other option is to try and run the docker build manually:

```
$ rm -r build/
$ docker run -it \
   -v "$PWD":/project \
   --rm lambci/lambda:build-python3.7 \
   pip install \
   --no-cache-dir \
   --no-color \
   --disable-pip-version-check \
   --upgrade \
   --find-links /project \
   --requirement /project/requirements.txt \
   --target /project/build
[...]
Installing collected packages: jmespath, six, python-dateutil, docutils, urllib3, botocore, s3transfer, boto3, cloudformation-cli-python-lib
Successfully installed boto3-1.10.37 botocore-1.13.37 cloudformation-cli-python-lib-0.0.1 docutils-0.15.2 jmespath-0.9.4 python-dateutil-2.8.0 s3transfer-0.2.1 six-1.13.0 urllib3-1.25.7
$ ls -1 build/
__pycache__
bin
boto3
boto3-1.10.37.dist-info
botocore
botocore-1.13.37.dist-info
cloudformation_cli_python_lib
cloudformation_cli_python_lib-0.0.1.dist-info
dateutil
docutils
docutils-0.15.2.dist-info
jmespath
jmespath-0.9.4.dist-info
python_dateutil-2.8.0.dist-info
s3transfer
s3transfer-0.2.1.dist-info
six-1.13.0.dist-info
six.py
urllib3
urllib3-1.25.7.dist-info
$
```

**Comment by ikben** [comment]
Congats on the release!

**Pull request closed without merging**
