### PR TITLE
Log Formatter

### PR DESCRIPTION
**Pull request by thoward-godaddy**
*Issue #, if available:* https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/issues/189

*Description of changes:* Adds optional argument to Hook to establish log formatter for handler.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by ammokhov — APPROVED** [review]
Thank you for your contribution. Looks good to me

**Review by Brianwithay21 — APPROVED** [review]
Changes look good to me for Hook types

**Comment by thoward-godaddy** [comment]
I'm not authorized to merge. Just wanted to check that this is in flight.

**Comment by thoward-godaddy** [comment]
Bueller?

**Comment by Brianwithay21** [comment]
apologies for the delay. Your change has been merged. Thank you for contributing

**Comment by thoward-godaddy** [comment]
No worries, appreciate you guys taking a look.

**Pull request merged**
