### PR TITLE
Patch for "unexpected keyword argument 'snapshotRequested'"

### PR DESCRIPTION
**Pull request by kallu**
*Issue #, if available:* #130 

*Description of changes:*
Adding support for 'snapshotRequired' argument similar to one already in Java -plugin.
https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/pull/316

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ammokhov** [comment]
> _Issue #, if available:_ #130
> 
> _Description of changes:_
> Adding support for 'snapshotRequired' argument similar to one already in Java -plugin.
> [aws-cloudformation/cloudformation-cli-java-plugin#316](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/pull/316)
> 
> By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

thanks for the PR, this issue should be fixed by #127 but the update has not been released yet.

**Review by ammokhov — COMMENTED** [review]
overall looks good but need to improve code coverage

**Comment by kallu** [comment]
I think is now obsolete as issue has been already fixed in cloudformation-cli-python-lib 2.1.3.

**Comment by tomwwright** [comment]
I'm encountering this issue currently cloudformation-cli-python-lib 2.1.3 -- how exactly is it fixed?

**Comment by kallu** [comment]
The First thing to verify is you have version 2.1.3 in requirements.txt as ```cfn init``` is not yet updated and by default will use an older version. After updating cloudformation-cli-python-lib requirement to 2.1.3 it worked for me.

**Pull request closed without merging**
